### ISSUE TITLE
Release 24kbps model 

### ISSUE THREAD

**Issue by Cortexelus** [descriptinc/descript-audio-codec#11]
According to your ablation study, the 24kbps model scored better. Can you release it?
<img width="956" alt="image" src="https://github.com/descriptinc/descript-audio-codec/assets/2453861/e35451fe-8b65-4f3a-9932-cd312d591990">

**Comment by listener17** [comment]
@Cortexelus: I guess the released model doesn't allow to run bitrates > 8 kbps, correct?

**Comment by ritheshkumar95** [comment]
Hey, please find the answers below:

1. The 44.1 KHz model was trained with a maximum bitrate of 8 kbps yes so it can't be run higher than that.
2. The 24 kbps ablation (44.1 KHz input sampling rate) was trained lesser than the final model. So we felt there wasn't a point in releasing it because it would still require more training.
3. Today we released a 24 KHz model with 24 kbps bitrate (exact same config as bitrate). See here: https://twitter.com/ritheshkumar_/status/1671886168106090501?s=20

**Comment by listener17** [comment]
OK @ritheshkumar95 - ignore my question, EMA = Exponential Moving Average.
