### ISSUE TITLE
Evaluation on 16KHz and 24KHz model?

### ISSUE THREAD

**Issue by seastar105** [descriptinc/descript-audio-codec#23]
there's thorough evaluation of 44.1KHz model in paper, 16K, 24K are not.

could you provide objective evaluation of each model?

**Comment by pseeth** [comment]
We trained these models after submission at community request, so we haven't evaluated the model yet. Will update with numbers at some point for these models, hopefully.

**Comment by ritheshkumar95** [comment]
We made the quantitative evaluations of the 24 KHz model, please find them here: 
https://twitter.com/ritheshkumar_/status/1671886168106090501?s=20

We don't have any current plans to evaluate the 16 KHz model since there isn't a publicly available model at 16 KHz that is easy to compare with. We welcome community contributions for that 🙏
