### ISSUE TITLE
Why does the 24kHz model use 32 codebooks?

### ISSUE THREAD

**Issue by Flux9665** [descriptinc/descript-audio-codec#31]
The 9 codebooks of the 44kHz model seemed to work really well. Even when I used only the first 4 codebooks, I found the quality totally sufficient for speech signals. That's why I was surprised to see that the 24kHz model uses 32 codebooks. What is the reason for that? I thought that a signal with a lower samplingrate could be compressed even better, i.e. fewer codebooks would be sufficient.

```
model = DAC()
model = load_model(model_type="24khz", tag="0.0.4")
print(model.n_codebooks)
>> 32
```

**Comment by pseeth** [comment]
Hey there, the 24khz model uses 32 codebooks so that we could directly compare to EnCodec. The configuration in terms of stride, number of codebooks, and sampling rate all match EnCodec. You're right though, that further compression should be possible!

However, quantizer dropout was used for this model as well. Here are the quantitative results at each bitrate:

<img width="265" alt="image" src="https://github.com/descriptinc/descript-audio-codec/assets/1054895/afe95f81-f421-4a97-a151-965bc0d9d5a4">

**Comment by Flux9665** [comment]
I see, thank you for the answer!

Are there any plans to release a 24kHz model trained with fewer codebooks as well? 

I'm not sure I understand the concept of these residual vector quantized codecs yet, so this might be a stupid question, but to reduce the bitrate of the model you just use fewer codebooks, right? So if the 24kHz model uses 32 codebooks to have a 24kbps bitrate, using only 8 codebooks corresponds to 6kbps?

**Comment by listener17** [comment]
@Flux: yes, 8 codebooks corresponds to 6kbps.

**Comment by NoFish-528** [comment]
@Flux9665 @listener17 @pseeth I have a question about 24khz. Do I only need to modify the following parameters when I train a 24khz model
```yaml
# Model setup
DAC.sample_rate: 24000
DAC.n_codebooks: 32

# Discriminator
Discriminator.sample_rate: 24000

```
